- README.md
This PR:
Description on how default-apps-vcd can be tested.
> fix couple typos

- CHANGELOG.md
- helm/default-apps-vcd/Chart.yaml
- helm/default-apps-vcd/ci/ci-values.yaml
- helm/default-apps-vcd/templates/_helpers.tpl
- helm/default-apps-vcd/templates/apps.yaml
- helm/default-apps-vcd/values.schema.json
- helm/default-apps-vcd/values.yaml
This PR:
- adds initial default apps
> add initial list of apps

- helm/default-apps-cloud-director/values.yaml
This PR add cert-manager as a default app.
> add cert-manager as a default app

- helm/default-apps-cloud-director/values.yaml
- renovate.json
Towards https://github.com/giantswarm/giantswarm/issues/23311
> Enable renovate to update app versions

- CHANGELOG.md
- helm/default-apps-cloud-director/Chart.yaml
This PR:
- adds `application.giantswarm.io/app-type: bundle` annotation
Towards https://github.com/giantswarm/giantswarm/issues/23882
> add app bundle annotation

- CHANGELOG.md
- helm/default-apps-cloud-director/values.schema.json
- helm/default-apps-cloud-director/values.yaml
> set ipam mode to kubernetes

- CHANGELOG.md
- helm/default-apps-cloud-director/templates/apps.yaml
- helm/default-apps-cloud-director/values.schema.json
- helm/default-apps-cloud-director/values.yaml
This PR:
- adds the observability bundle
Description on how `observability bundle` can be tested.
> Add observability bundle

- CHANGELOG.md
> bump cpi to 0.2.0 in changelog

- CHANGELOG.md
- helm/default-apps-cloud-director/Chart.yaml
This PR:
- Change `compatibleProvider` from `vcd` to `cloud-director`
> Changed compatibleProvider from vcd to cloud-director

- CHANGELOG.md
- helm/default-apps-cloud-director/values.yaml
> Upgrade observability-bundle

- CHANGELOG.md
- helm/default-apps-cloud-director/values.yaml
Towards https://github.com/giantswarm/giantswarm/issues/25659
> Create default network policies with cilium

- CHANGELOG.md
- helm/default-apps-cloud-director/values.yaml
> Bump cloud-provider-cloud-director to 0.2.1

- CHANGELOG.md
- helm/default-apps-cloud-director/values.yaml
This PR:
- upgrades the observability bundle to ensure the prometheus agent is restarted if the MC prometheus is flooded
@giantswarm/team-rocket do you have some automated testing on cloud director?
> Upgrade observability bundle

- CHANGELOG.md
- helm/default-apps-cloud-director/templates/apps.yaml
This PR:
- fixes the name of templated secrets.
> fix secret name to pass validation

- CHANGELOG.md
- helm/default-apps-cloud-director/values.schema.json
- helm/default-apps-cloud-director/values.yaml
Towards https://github.com/giantswarm/giantswarm/issues/23449
Works together with https://github.com/giantswarm/cluster-cloud-director/pull/78
> Remove CNI/CPI/CSI

- CHANGELOG.md
- helm/default-apps-cloud-director/templates/apps.yaml
see https://gigantic.slack.com/archives/C02GDJJ68Q1/p1679688523105139 for (hopefully) some more context.
This PR:
- corrects the user secret name (again)
> correct user secret values name

- CHANGELOG.md
- helm/default-apps-cloud-director/values.schema.json
> fix missing schema

- CHANGELOG.md
- helm/default-apps-cloud-director/values.yaml
Issue: https://github.com/giantswarm/giantswarm/issues/25482
This PR:
> etcd-kubernetes-resources-count-exporter

- CHANGELOG.md
> update changelog with dependency changes

- helm/default-apps-cloud-director/values.yaml
Towards https://github.com/giantswarm/giantswarm/issues/28112#event-11278647976
> enable ciliumNetworkPolicy obs bundle

- helm/default-apps-cloud-director/Chart.yaml
This PR:
- adds chart icon to unblock all CI pipelines
> Add missing icon

- CHANGELOG.md
- helm/default-apps-cloud-director/templates/apps.yaml
- helm/default-apps-cloud-director/values.schema.json
- helm/default-apps-cloud-director/values.yaml
Same as https://github.com/giantswarm/default-apps-aws/pull/380
context: https://gigantic.slack.com/archives/C01BYMF6RN0/p1704989737078779
> Use YAML object for app configuration values

- .github/pull_request_template.md
- renovate.json5
This PR:
Automatically triggers E2e tests on new PRs.
Issue: https://github.com/giantswarm/giantswarm/issues/29379
> Automatically trigger e2e test on PRs.

- CHANGELOG.md
- Makefile
- helm/default-apps-cloud-director/README.md
This PR:
Towards https://github.com/giantswarm/giantswarm/issues/29628
I want to add a Chart README to be embedded in our docs based on the [schemadocs](https://github.com/giantswarm/schemadocs) project
/run cluster-test-suites
> Generate schema docs in the project

- CHANGELOG.md
- helm/default-apps-cloud-director/values.yaml
towards https://github.com/giantswarm/giantswarm/issues/31155
/run cluster-test-suites
> Add observability-policies app
